// Generated by CoffeeScript 1.11.1
(function() {
  var ArgumentParser, argparser, argv, compile, data, fs, html, packageInfo, parse, parseOptionSet, ref;

  ref = require('./'), compile = ref.compile, parse = ref.parse;

  fs = require('fs');

  packageInfo = require('../package');

  ArgumentParser = require('argparse').ArgumentParser;

  argparser = new ArgumentParser({
    version: packageInfo.version,
    addHelp: true,
    description: packageInfo.description
  });

  parseOptionSet = argparser.addMutuallyExclusiveGroup();

  parseOptionSet.addArgument(['--data', '-d'], {
    type: 'string',
    help: 'The path to the JSON file, containing data to pass to the compiler.',
    required: false
  });

  parseOptionSet.addArgument(['--parse', '-p'], {
    help: 'Flag to parse the file into an AST, rather than compile it.',
    action: 'storeTrue',
    defaultValue: false,
    required: false
  });

  argv = argparser.parseArgs();

  if (argv.data) {
    data = JSON.parse(fs.readFileSync(argv.data));
  }

  html = '';

  process.stdin.on('data', function(chunk) {
    return html += chunk;
  }).on('end', function() {
    return process.stdout.write(argv.parse ? JSON.stringify(parse(html)) : compile(html, data));
  });

}).call(this);
